#server:
  #port: 8081
  #servlet:
    #context-path: /
    
spring:
  #mvc:
    #view:
      #prefix: /resources/templates/
      #suffix: .html

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: cos
    password: 1234
  jpa:
    open-in-view: true
    hibernate:
      #ddl-auto: create
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true 
  devtools:
    livereload:
      enable: true
    freemaker:
      cache: false
  thymeleaf:
    prefix: classpath:templates/
    #suffix: .html
    cache: false